// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Quitly.Api.Persistence;

#nullable disable

namespace Quitly.Api.Persistence.Migrations
{
    [DbContext(typeof(QuitlyDbContext))]
    partial class QuitlyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Quitly.Api.Domain.Entities.CheckIn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<Guid>("HabitId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Mood")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HabitId");

                    b.HasIndex("UserId", "Day")
                        .IsUnique();

                    b.ToTable("check_ins", (string)null);
                });

            modelBuilder.Entity("Quitly.Api.Domain.Entities.CheckInTrigger", b =>
                {
                    b.Property<Guid>("CheckInId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TriggerId")
                        .HasColumnType("uuid");

                    b.HasKey("CheckInId", "TriggerId");

                    b.HasIndex("TriggerId");

                    b.ToTable("check_in_triggers", (string)null);
                });

            modelBuilder.Entity("Quitly.Api.Domain.Entities.Habit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartedOn")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Active")
                        .IsUnique()
                        .HasFilter("\"Active\" = true");

                    b.ToTable("habits", (string)null);
                });

            modelBuilder.Entity("Quitly.Api.Domain.Entities.RecoveryPlanStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DueWithinHours")
                        .HasColumnType("integer");

                    b.Property<Guid>("RelapseId")
                        .HasColumnType("uuid");

                    b.Property<string>("StepText")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RelapseId");

                    b.HasIndex("UserId");

                    b.ToTable("recovery_plan_steps", (string)null);
                });

            modelBuilder.Entity("Quitly.Api.Domain.Entities.Relapse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContextNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HabitId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HabitId");

                    b.HasIndex("UserId");

                    b.ToTable("relapses", (string)null);
                });

            modelBuilder.Entity("Quitly.Api.Domain.Entities.Reminder", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("PassivePromptEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("PromptTone")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("reminders", (string)null);
                });

            modelBuilder.Entity("Quitly.Api.Domain.Entities.Streak", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentStreakDays")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("LastAbstinentDay")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("LastNonAbstinentDay")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("streaks", (string)null);
                });

            modelBuilder.Entity("Quitly.Api.Domain.Entities.Trigger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("triggers", (string)null);
                });

            modelBuilder.Entity("Quitly.Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Quitly.Api.Domain.Entities.WeeklyInsight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AbstinentDays")
                        .HasColumnType("integer");

                    b.Property<int>("CheckInCount")
                        .HasColumnType("integer");

                    b.Property<int>("Confidence")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MoodTrend")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SummaryText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("TopTriggers")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("WeekStart")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "WeekStart")
                        .IsUnique();

                    b.ToTable("weekly_insights", (string)null);
                });

            modelBuilder.Entity("Quitly.Api.Domain.Entities.CheckIn", b =>
                {
                    b.HasOne("Quitly.Api.Domain.Entities.Habit", "Habit")
                        .WithMany("CheckIns")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quitly.Api.Domain.Entities.User", "User")
                        .WithMany("CheckIns")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Quitly.Api.Domain.Entities.CheckInTrigger", b =>
                {
                    b.HasOne("Quitly.Api.Domain.Entities.CheckIn", "CheckIn")
                        .WithMany("CheckInTriggers")
                        .HasForeignKey("CheckInId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quitly.Api.Domain.Entities.Trigger", "Trigger")
                        .WithMany("CheckInTriggers")
                        .HasForeignKey("TriggerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CheckIn");

                    b.Navigation("Trigger");
                });

            modelBuilder.Entity("Quitly.Api.Domain.Entities.Habit", b =>
                {
                    b.HasOne("Quitly.Api.Domain.Entities.User", "User")
                        .WithMany("Habits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Quitly.Api.Domain.Entities.RecoveryPlanStep", b =>
                {
                    b.HasOne("Quitly.Api.Domain.Entities.Relapse", "Relapse")
                        .WithMany("RecoveryPlanSteps")
                        .HasForeignKey("RelapseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quitly.Api.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Relapse");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Quitly.Api.Domain.Entities.Relapse", b =>
                {
                    b.HasOne("Quitly.Api.Domain.Entities.Habit", "Habit")
                        .WithMany("Relapses")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quitly.Api.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Quitly.Api.Domain.Entities.Reminder", b =>
                {
                    b.HasOne("Quitly.Api.Domain.Entities.User", "User")
                        .WithOne("Reminder")
                        .HasForeignKey("Quitly.Api.Domain.Entities.Reminder", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Quitly.Api.Domain.Entities.Streak", b =>
                {
                    b.HasOne("Quitly.Api.Domain.Entities.User", "User")
                        .WithOne("Streak")
                        .HasForeignKey("Quitly.Api.Domain.Entities.Streak", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Quitly.Api.Domain.Entities.WeeklyInsight", b =>
                {
                    b.HasOne("Quitly.Api.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Quitly.Api.Domain.Entities.CheckIn", b =>
                {
                    b.Navigation("CheckInTriggers");
                });

            modelBuilder.Entity("Quitly.Api.Domain.Entities.Habit", b =>
                {
                    b.Navigation("CheckIns");

                    b.Navigation("Relapses");
                });

            modelBuilder.Entity("Quitly.Api.Domain.Entities.Relapse", b =>
                {
                    b.Navigation("RecoveryPlanSteps");
                });

            modelBuilder.Entity("Quitly.Api.Domain.Entities.Trigger", b =>
                {
                    b.Navigation("CheckInTriggers");
                });

            modelBuilder.Entity("Quitly.Api.Domain.Entities.User", b =>
                {
                    b.Navigation("CheckIns");

                    b.Navigation("Habits");

                    b.Navigation("Reminder");

                    b.Navigation("Streak");
                });
#pragma warning restore 612, 618
        }
    }
}
